project:
  type: website
  output-dir: _site
  resources: 
    - "*.mp4"
    - "*.txt"
    - "*.csv"

lang: ru

execute:
  freeze: auto

filters:
  - course

website:
  navbar:
    left: 
        - program.md
        # - homework.md 
    title: false
  repo-url: https://github.com/glkarpov/ptms_mds_hse_26
  repo-branch: main
  repo-actions: [edit]
  search: 
    location: navbar
    type: textbox
  twitter-card: true
  open-graph: true
  favicon: favicon.svg
